### ISSUE TITLE
Global Search (GSoC) Task list

### ISSUE THREAD

**Issue by kb0304** [RocketChat/Rocket.Chat#10800]
### Coding Task List
- [ ] Indexing `type` of `message` for system messages, etc.
- [ ] Indexing attachment content : Doc files, PDF, other formats
- [ ] Advanced search filters (functionality implementation)
    - [ ] Filter by date range
    - [ ] Filter by message type
    - [ ] Filter by user
- [ ] UI for advance search filter
    - [ ] Filtering based on parameters and their values in search text itself (like Github PR search) eg. “author:karan.bedi” would filter all the messages by user with username: karan.bedi
    - [ ] Dropdown choice for values of each parameter

**Comment by mrsimpson** [comment]
Some small ideas, more as an "I thought of" - not as a "I thought about" ;)
@tkurz surely has thought about it, but is currently not easy to grasp...

- Indexing attachments => See Apache Tika and [its integration with Solr](https://lucene.apache.org/solr/guide/7_3/uploading-data-with-solr-cell-using-apache-tika.html)
- Have you verified the filter-criteria are not already part of the Solr-Index? I don't know the index design.
- With respect to the UI, I think it should be harmonized with the directory. There should be only one entry point to browse what's inside Rocket.Chat. I appreciate text-based filters, but particularly non-teckies also like clickable form-like elements. It may be an idea to implement a nice facetting-display which you can browse and drill-down.

**Comment by tkurz** [comment]
The fields that are mentioned for filters are already part of the solr index, yes.

**Comment by kb0304** [comment]
@mrsimpson 
I will look into Indexing attachments and would surely take it up in the coming time.
For UI, can you please elaborate what do you mean by 'harmonized with the directory' part and also, could you please give some sample implementations of these form-like elements?

**Comment by mrsimpson** [comment]
@kb0304 

> can you please elaborate what do you mean by 'harmonized with the directory' part
I'll try: There are two "searches" (identified by a magnifier symbol) on the UI already but they don't fulfill this purpose: The magnifier in the channel list finds only subscribed rooms and users, the find in the tabbar of the room finds messages - and optionally now also cross-room - but is only accessible once a room is opened. 
IMHO, there has to be one - and only one - access to all of that. And it has to be available independent of being in in a room. And this is the directory (which is reachable using the globe-symbol). It is currently **the** way of finding stuff in Rocket.Chat. A global search UI has to be aligned with that. If I was to judge, I'd kill all the other search symbols and change the symbol of the directory to a magnifier - and use it to open the global search UI which can be based upon the current directory.
I hope this was more clear now.

> could you please give some sample implementations of these form-like elements

I personally love the way [Adobe Lightroom provides filtering](https://helpx.adobe.com/lightroom/help/finding-photos-catalog.html). Also, [SAP UI5 has a nice filter-UI-component](https://experience.sap.com/fiori-design-web/filter-bar/#layout) - But I can't help you with a library closer to RC.

**Comment by mrsimpson** [comment]
@kb0304 what did you finally do?

**Comment by kb0304** [comment]
Hi @mrsimpson
My project is changed to Integration of Voice Recognition API and Speech2Text engines. I have been working on the same.
