### ISSUE TITLE
[WIP-FEATURE-GSoC] Livechat: Real-Time Visitor Monitoring

### ISSUE THREAD

**Issue by knrt10** [RocketChat/Rocket.Chat#14642]
# **Livechat: Real-Time Visitor Monitoring**

This issue is part of my GSoC process. Will be tracking all my work here. This issue will be divided into 3 sub phases, which will help in tracking the work more efficiently. This is initial draft of issue. It will be updated as the GSoC period commences. Happy Coding :fire: :fireworks: 

**Mentor**:- [Renato Becker](https://github.com/renatobecker)

### Phase 1
----------------------------------------------------
This phase will mainly focus on working on sending new information from client side to RC admin dashboard(_which I will design_).

#### Week 1

- [x] Get location of user, either using API or any other way. API might be easy way but it might not be free, so might have to find an alternative way for it.
- [x] Implement getting location for user in LiveChat Client 

#### Week 2
- [x] Implement methods on [JS.SDK](https://github.com/RocketChat/Rocket.Chat.JS.SDK) of RC to send data from client side [Livechat](http://github.com/RocketChat/Rocket.Chat.Livechat/) to dashboard(RC main repo). This will include writing on different methods to send different type of information from client side to server.

#### Week 3 
- [x] Start designing admin dashboard. **This is very important.** 
- [x] Add location information of user received from client side to dashboard
- [x]  Get code reviewed from Mentor.

#### Week 4 
- [x] Continue working on admin dashboard. More important fix UI changes
- [x] Write docs for changes and test cases if possible.

### Phase 2
----------------------------------------------------
This phase will mostly focus on working on admin dashboard and writing API for new implementation on LiveChat

#### Week 1 
- [x] Implement current state of client i.e Chatting, browsing, registered to chat on LiveChat and send it using JS SDK.
- [x] Fix bugs on UI for admin dashboard
- [x] Write docs for changes

#### Week 2 
- [x] Add user browsing information on admin dashboard.
- [x] Create API for new admin dashboard using data stored in new collection **rocketchat_livechat_visitor_sessions** and write corresponding tests for it.

#### Week 3
- [x] Write docs for API created above
- [x] Fix Admin UI and any other bugs found
- [x] Get code review from Mentor

### Phase 3
--------------------------------------------------------------
This phase will mostly focus on completing rest of the things on LiveChat client and adding all changes to admin dashboard. 

#### Week 1 
- [x] Implement adding new information about user on information flex tab on the livechat room. Flex tab is the information tab on side of a room. 
- [x] Fix issues on Admin Dashboard.

#### Week 2 
- [x] Start working on adding sentiment analysis of users once they close the chat to the flex tabs, to be used in case to help other agents when they return.

#### Week 3 
- [x] Complete adding sentiment analysis of user to both dashboard and flex tab of livechat room.
- [x] Fix bugs and improve UI for admin dashboard.
- [x] Write docs for changes.
- [x] Get final code reviewed from Mentor.

**Comment by knrt10** [comment]
Keeping Track of PR's

## Week 1 & 2 

- [ ] [Server Side](https://github.com/RocketChat/Rocket.Chat/pull/14765) :-  This one added location data to new collection `rocketchat_livechat_sessions`
-  [ ] [Client Side](https://github.com/RocketChat/Rocket.Chat.Livechat/pull/242):- This sent location data from client side to server side when livechat is connected
- [ ] [SDK](https://github.com/RocketChat/Rocket.Chat.js.SDK/pull/82):- This is an API which helped to send data from client side to server.

**Comment by knrt10** [comment]
## Week 3

- [ ] Started work on [Admin Dashboard](https://github.com/RocketChat/Rocket.Chat/pull/14813).

**Comment by engelgabriel** [comment]
https://github.com/RocketChat/feature-requests/issues/135
