### ISSUE TITLE
Incoming WebHooks

### ISSUE THREAD

**Issue by engelgabriel** [RocketChat/Rocket.Chat#1501]
#### Implement 100% compatible Slack Incoming Webhooks API.
See spec here: https://api.slack.com/incoming-webhooks

##### Final acceptance test

This sample curl command for posting to a channel:

```sh
curl -X POST --data-urlencode 'payload={"text": "This is posted to <#general> and comes from *monkey-bot*.", "channel": "#general", "username": "monkey-bot", "icon_emoji": ":monkey_face:"}' https://demo.rocket.chat/services/TOKEN
```

Will be displayed in the #general channel as:

![image](https://cloud.githubusercontent.com/assets/1000217/11430767/a606f29a-9472-11e5-8a0f-981a8027f4ad.png)

##### Subtasks

- [ ] Update message template to support overwrite the `avatar` with `icon_url` or `icon_emoji`
- [x] Update message template to support overwrite the `username`
- [x] Create a Incoming WebHooks admin page
- [x] Manage integration token as `users` with special type

![image](https://cloud.githubusercontent.com/assets/1000217/11430900/d0cdcba0-9474-11e5-9bf3-9367620dbeee.png)

**Comment by engelgabriel** [comment]
#1528 is a duplicate of this issue

**Comment by vetash** [comment]
I want it so much.

**Comment by graywolf336** [comment]
@vetash It was added with #1613. :smile:

**Comment by geekgonecrazy** [comment]
@vetash coming to a Rocket.Chat near you.  Soon ;)

**Comment by engelgabriel** [comment]
It will be on master on monday.

**Comment by vetash** [comment]
Current version in master.zip is include integration is worked fine! :+1:  Thank you very much! But does not work on private chanel :(

**Comment by vetash** [comment]
Also need to add "attachments" and other formatting like is slack
https://api.slack.com/docs/formatting 
Is very usefull for messages of monitoring system like zabbix or something. Please add it too :smile:

**Comment by engelgabriel** [comment]
that's all done develop @vetash

**Comment by vetash** [comment]
Oh. Sorry for my inattentive

**Comment by engelgabriel** [comment]
Ehehehe.. no worries

**Comment by juanluisbaptiste** [comment]
When this feature is ready, we will be able to use for example this script ? https://github.com/ericoc/zabbix-slack-alertscript

**Comment by geekgonecrazy** [comment]
@juanluisbaptiste This feature is actually complete 😄 

And yes absolutely should work with Rocket.Chat.  Just create an integration in Administration->Integrations  Then take the url and use just like you would the slack url from that projects README.

Here: https://github.com/ericoc/zabbix-slack-alertscript/blob/master/slack.sh#L4 you would just put your Rocket.Chat integration url

**Comment by juanluisbaptiste** [comment]
Excellent, thanks !
