### ISSUE TITLE
Brute-Force Protection

### ISSUE THREAD

**Issue by dmeier86** [RocketChat/Rocket.Chat#6152]
Rocket.Chat Version: 0.51.0
Running Instances: 1
DB Replicaset OpLog:
Node Version: 4.5.0

See:
https://github.com/RocketChat/Rocket.Chat/issues/2737
We do need a brute-force-protection or at least an implementation for fail2ban.
Failed logins are written in the Logs at Admin-Interface - but fail2ban can't read those.

Any Solution anyone?

**Comment by nixwizard** [comment]
When dealing with distributed brutefroce, reCaptcha it more effective than banning IPs. It would be nice to have a possibility to turn it on for the login process.

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Closing this in favour of #2737. If you think this is not correct, please get back to me :)

Cheers
Thomas

**Comment by ruKurz** [comment]
I like the title of this issue! It states out the real intention: "prevent brute force attacks" (unfortunately the description is reduced to log failed login attempts).

To fend off Bruteforce attacks effectively there are a lot of things you can do against it, e.g.

- [ ] Strong passwords  (implemented | #9857)
- [ ] Two-Factor Authentication (implemented | but not mandatory #9233)
- [ ] Do not use "admin" as username (possible | by design)
- [ ] Limit number of invalid logins (open | #2737 this is not just about logging, but about limiting logins)
- [ ] IP Whitelist / Blacklisting (open | instrucure or software?)

Some of them are implemented at the application level and some at the infrastructure level. While logging of failed login attempts is taken over by the application, fail2ban is a system component, outside the runtime of the application.  For example, failed logins could also be stored in the database. And after a configurable number of failed attempts, the affected user account is then locked.

**Comment by TwizzyDizzy** [comment]
>  For example, failed logins could also be stored in the database. And after a configurable number of failed attempts, the affected user account is then locked.

This is not a good idea, because then I can lock you out of your account.

Tarpitting (increasing waiting time before new login can be tried)  based on the source IP seems to be a good way.

This way you cannot lock my account because if you try, my logins are still not tarptitted because I (usually) am from a different IP.

Cheers
Thomas

**Comment by ruKurz** [comment]
OK! Delaying further authentication attempts is the first step, but after several failed attempts the user ID must be blocked. This is also recommended by the BSI (ORP.4).

For both increasing delay and account locking, login attempts must be stored in the database.
