### ISSUE TITLE
Review closed unmerged PRs from kable-wilmoth

### ISSUE THREAD

**Issue by engelgabriel** [RocketChat/Rocket.Chat#8012]
@kable-wilmoth had a few PRs but he was probably annoyed that it took us to long to review it. Let's review the PRs and try to turn the good enhancement they offered into new PRs and merge them to the next release.

https://github.com/RocketChat/Rocket.Chat/pulls?q=is%3Apr+author%3Akable-wilmoth

- [x] Attachments - for now at least post a message that a file was uploaded #6309
- [x] Fix for keeping a room hidden after activity #6299
- [x] Reactions setting #6285 
- [x] Support for dynamic slack and rocket channels #6282

**Comment by kable-wilmoth** [comment]
Some of them aren't valid anymore.  Let me take a look at them and see which ones still make sense etc.  Thanks for jumping on these though.

**Comment by jszaszvari** [comment]
Nobodys looked at this either.. Nearly 2 months to get a comment from a staff member..

https://github.com/RocketChat/Rocket.Chat/pull/7454

**Comment by lindoelio** [comment]
Hey @kable-wilmoth! I can work with these PRs for the target. Let me know which are valid. :-)

@jszaszvari I will work on your suggestion also.
