### ISSUE TITLE
Make permalinks work across different sandstorm apps.

### ISSUE THREAD

**Issue by nicolas-arnold** [RocketChat/Rocket.Chat#9293]
This is a feature request for the **sandstorm** version of Rocket.Chat. I think it would be a great enhancement and a logic conclusion due to the concept of a production suite.

The "permalink"-function should produce a link, that can be used across the plattform. For now it only works inside the Chat itself.

### Expected Behaviour:

1. Copy a permalink to clipboard
2. Paste it in a Pad inside, or another instance of Rocket.Chat 
3. If you click it (and have the permissions) you get directly to the linked message in the chat

### Use Case:

"Click the following link to see, what we discussed in that chat and why we came to this conclusion: _permalink_"

I tried to combine the created Permalink with the "Sandstorm Webkey" but it asked for a password.
I'm not sure if it is possible to instead of opening a new tab, the link could "activate the chat-grain" without leaving the current browser tab...

### ToDo: (what I think needs to be done)

- [ ] Create a permalink that works inside sandstorm, or from anywhere (like E-Mail) using the webkey of the Rocket.Chat-grain
- [ ] Make Rocket.Chat interpret it as before (as a local link with 127.0.0.1 ...)
- [ ] In the longterm, maybe one want a setting for that, to decide if both link types are supported, or only local, or only global...

Thanks a lot, the permalink already is a great feature and the potential is huge for an advanced usage across sandstorm apps, allowing for easy cross-referencing.

**Comment by ggazzo** [comment]
we dont support anymore sandstorm =/
