### ISSUE TITLE
Contextual bar issues

### ISSUE THREAD

**Issue by karlprieb** [RocketChat/Rocket.Chat#9466]
- [x] reduce avatar size on members list
- [x] remove view all button on user details
- [x] open user details on click on members list
- [x] remove mail messages button from room info
- [x] User info panel padding
- [x] fix username field on room info when you're on dm
- [x] Save Changes button padding #9463
- [x] inputs are unstyled inputs on admin/registration pages
- [x] new integration button broken
- [x] 'Set as owner/leader/moderator' icons on member #9473
- [x] Add users tab icon #9474
- [x] finish notifications preferences panel
- [x] finish mail messages panel
- [x] outgoing integration history entries look terrible and unstyled
- [x] header "user info"
- [x] scrollbars are not working on firefox #9380
- [x] the 'unread messages' sign on room are on top of the contextual bar panels
![image](https://user-images.githubusercontent.com/9200155/35285879-9835bad4-0045-11e8-94e8-a0f956312390.png)
- [ ] when channel list mode is set to sort by activity only shows favorites channels on sidebar #9475
