### ISSUE TITLE
Livestream & Broadcasting on Rocket.Chat

### ISSUE THREAD

**Issue by gdelavald** [RocketChat/Rocket.Chat#9543]
## Description:

This feature integrates video livestream and broadcasting to Rocket.Chat servers. When enabled, the Livestream tab open the possibility of adding embedded video links to a channel which every user can access and watch through the new popout component. The main objective of the feature is enable a better communication within streaming communities, we also are working with Brave and BAT to enhance the compatibility with the platform so content creators are rewarded not only by creating a better community but for their efforts as well through Basic Attention Token.

The first phase of the integration is focused on the channel livestreaming platform, creation of the popout component that enables watching a livestream while changing conversation channel within Rocket.Chat.

The second phase of the integration is related to the broadcasting interface and how users can broadcast directly from their Rocket.Chat instance once connected with an OAuth provider (Youtube will be used at first), this will also improve the Livestream functionalities by having automated updates from the broadcaster to selected channels.

### Phase 1 - Livestream UI ([Pull Request](https://github.com/RocketChat/Rocket.Chat/pull/9255))

- [x] Admin settings to enable Livestream feature
- [x] Livestream tab on channel contextual sidebar
- [x] Enable admins to set URL and streaming mode (audio or video)
- [x] Parse different URLs to create a embeddable link for the livestream (Youtube for now)
- [x] Create Popout component following the design provided
- [x] Create modal window that persists video through a change of channels
- [x] Enable users to watch livestream through the popout component
- [x] Allow users to move the popout by drag-n-drop
- [x] Allow users to minimize the video without it being stopped
- [x] Allow users to play/pause/mute the livestream (only for himself)

### Phase 2 - Broadcasting UI

- [ ] Admin settings to enable and configure broadcasting settings
- [ ] Extend Livestream channel sidebar
- [ ] Integrate youtube streaming API into Rocket.Chat 
- [ ] Enable users with permission to broadcast to their youtube channel (once configured in the admin panel)

**Comment by divergefx** [comment]
This is amazing implementation.  It would be even more amazing if I could resize the popout modal.  How difficult would that be?

**Comment by gdelavald** [comment]
@divergefx Hey, that is an enhancement that we plan as soon as we get the phase 2 (broadcasting) done. Also, feel free to contribute, the popout style can be found in the popout.css and resizing it would need some Javascript implementation (most likely on popout.js file).
Thanks for the feedback :+1:

**Comment by Darktimr** [comment]
It would be great, if other users in this channel get an popup on the side by entering the channel.

**Comment by gdelavald** [comment]
@Darktimr we are looking into a better way to notify users that a channel has an active broadcast, right now the users has to be actively looking for it to find it and we don't feel like this is the best UX right now.
Thanks for your suggestion, this is something we are aiming to improve in the future.

**Comment by Darktimr** [comment]
@gdelavald good :)

You could add something like a playbar before the rouminformation icon. 

Like this or something similar: [playbar](https://www.google.de/search?q=musik+play+bar&source=lnms&tbm=isch&sa=X&ved=0ahUKEwic3Iv5tvDZAhVL_aQKHT0aDG4Q_AUICygC&biw=1920&bih=1069#imgrc=l7M9gOuSTqEOAM:)

**Comment by rasos** [comment]
It would be great if any live streaming service would be accepted to broadcast to.  Currently, even  if the Broadcasting Client ID field is empty, a YouTube login pops up. I suggest that if that field is empty, you do not require any authentication.  Streaming servers like PeerTube 3.0 only require a URL and a key to stream to.

Jitsi Meet now also allows to enter a YouTube stream key **or** a `rtmp://mystreamingserver:1935/live/streamkey` URL.

**Comment by narayanan-ka** [comment]
Does Rocketchat have a Self hosted Live Video Conferencing and Live Streaming Feature or do we have to rely on thrid party APIs like Youtube ?
