### ISSUE TITLE
Android UI experience checklist

### ISSUE THREAD

**Issue by ninja-** [RocketChat/Rocket.Chat#998]
- [ ] - fix slow window resizing when you bring the android keyboard
- [ ] - get rid of the bar on the right because it takes a lot of space
- [ ] - ability to swype from the left to get the list of channels

swyping from the left works on the "internet" android app but not on chrome...weird
after swyping the bar back, the icons panel becomes blank....the search and userlist icons disappear

**Comment by ninja-** [comment]
any thoughts?

**Comment by skemb321** [comment]
@ninja- do  you experience any issues re uploading images on android app?

**Comment by geekgonecrazy** [comment]
I believe most of these are no longer relevant.  If any are please create an issue on the cordova repo: https://github.com/RocketChat/Rocket.Chat.Cordova
